volumes:
  mongodb_data:

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27071:27071"
    volumes:
      - "mongodb_data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
